on:
  push:
    branches:
      - main
  pull_request:

jobs:
  editorconfig-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Hard-coded commit, because the latest changes aren't tagged.
      - uses: editorconfig-checker/action-editorconfig-checker@d4fca16fc71adef10fbe101903b654449fa9570c
        with:
          version: 2.7.0
      - run: editorconfig-check
